config/routes.rb
Rails.application.routes.draw do
  resources :categories do 
    resources :charts
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attached_validator.rb
class AttachedValidator < ActiveModel::EachValidator
    def validate_each(record, attribute, value)
        record.errors.add(attribute, :attached, options) unless value.attached?
    end
end

app/models/category.rb
class Category < ApplicationRecord
    scope :recent, -> { where('created_at > ?', 1.week.ago) }
    has_many :charts, dependent: :destroy
    validates :title, presence: true,
                    length: { minimum: 5}
end

app/models/chart.rb
class Chart < ApplicationRecord
  belongs_to :category
  has_one_attached :image
  validates :image, attached: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
    def create 
        @category = Category.find(params[:category_id])
        @chart = @category.charts.create(comment_params)
        @errors_messages = @chart.errors.messages       
        full_error_message = ""
        @errors_messages.each {|key, value| full_error_message = "#{key} " + value[0].to_s}
         if @errors_messages.any? 
            flash[:notice] ='ERROR: Chart was not created because ' + full_error_message.to_s
         end 
        redirect_to category_path(@category)
    end 

    def destroy 
        @category = Category.find(params[:category_id])
        @chart = @category.charts.find(params[:id])
        @chart.destroy
        redirect_to category_path(@category)
    end 

    def edit 
        @category = Category.find(params[:category_id])
        @chart = Chart.find(params[:id])
    end 

    def update
        @category = Category.find(params[:category_id])
        @chart = Chart.find(params[:id])
        @chart.update_attributes(comment_params)
        redirect_to category_path(@category)
    end 

    def show 
        @category = Category.find(params[:category_id])
        @chart = Chart.find(params[:id])
    end 

    private 
    def comment_params
        params.require(:chart).permit(:blindrange, :situation, :opponent, :image )
    end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h2> Categories </h2>
<p> Click on a category to get more details </p>
<ul class="nav nav-pills nav-fill">
    <% @categories.each do |category| %>
      <% category_title = category.title%>
      <li class="nav-item  d-flex justify-content-around">
        <%= link_to category_title, category, class: "nav-link btn btn-primary" %> 
      </li>
    <% end %>
</ul>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% if notice %>
<p id="notice" class="alert alert-danger"><%= notice %></p>
<% end%>
<div class="justify-content-center">
<%= link_to 'Back', categories_path, class: "btn btn-primary" %>
</div>

<h2 d-flex align-items-center> CATEGORIES</h2>
<ul class="nav nav-pills nav-fill">

    <% @categories.each do |category| %>
      <% category_title = category.title%>
      <li class="nav-item d-flex justify-content-around">
        <%= link_to category_title, category, class: "nav-link btn btn-primary" %> 
      </li>
    <% end %>
</ul>


<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<div style="display:flex">
<% @category.charts.each do |chart| %>

  
  <div class="p-2 bd-highlight">
  <strong>Blind range :</strong>
   <p style="font-size: 40px">
    <%= chart.blindrange %>
  </p>
  <% if chart.situation[0] == "3"%>
   <div style="width:800px; height:auto">
    <%= image_tag(chart.image, style: "width:100%")%>
      <%= link_to 'Destroy', category_chart_path(@category, chart), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Edit', edit_category_chart_path(@category, chart) %>
      <%= link_to 'Show', edit_category_chart_path(@category, chart) %>
  </div>
  <% else %>
   <div style="width:400px; height:auto">
    <%= image_tag(chart.image, style: "width:100%")%>
      <%= link_to 'Destroy', category_chart_path(@category, chart), method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Edit', edit_category_chart_path(@category, chart) %>
      <%= link_to 'Show', edit_category_chart_path(@category, chart) %>
  </div>
  <% end %>
  </div>
 
<% end %>
</div>



<h2>Add a chart:</h2>

<%= render 'charts/form'%>

app/views/charts/_chart.html.erb
<p>
    <strong>Blind Range:</strong>
    <%= chart.blindrange%>
</p>

<p>
    <strong>Situation :</strong>
    <%= chart.situation%>
</p>

<p>
    <strong>Opponent type:</strong>
    <%= chart.opponent%>
</p>

app/views/charts/_form.html.erb
<%= form_with(model: [ @category, @category.charts.build ],
local: true) do |form| %>
<p>
    <%= form.label :blindrange %>
    <%= form.text_field :blindrange %>
</p>

<p>
    <%= form.label :situation %>
    <%= form.text_field :situation %>
</p>

<p>
    <%= form.label :opponent %>
    <%= form.text_field :opponent %>
</p>

 <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>


<p> 
    <%= form.submit %>
</p>
<% end %>

app/views/charts/edit.html.erb
<%= form_with(model: [@category, @chart], local: true) do |form| %>
    <p>
        <%= form.label :blindrange %>
        <%= form.text_field :blindrange %>
    </p>

    <p>
        <%= form.label :situation %>
        <%= form.text_field :situation %>
    </p>

    <p>
        <%= form.label :opponent %>
        <%= form.text_field :opponent %>
    </p>

    <div>
        <%= form.label :image %>
        <%= form.file_field :image %>
    </div>


    <p> 
        <%= form.submit %>
    </p>
<% end %>

app/views/charts/show.html.erb
<p>
    <strong>Blind Range:</strong>
    <%= @chart.blindrange%>
</p>

<p>
    <strong>Situation :</strong>
    <%= @chart.situation%>
</p>

<p>
    <strong>Opponent type:</strong>
    <%= @chart.opponent%>
</p>


    <strong>Chart </strong>
     <div>
        <%= image_tag(@chart.image, style: "width:400px")%>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChartOrganiser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>